name: build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "[7.4] Build and push"
        id: docker_build_74
        uses: docker/build-push-action@v2
        with:
          push: true
          file: 7.4.Dockerfile
          tags: adhocore/lemp:7.4-alp3.13,adhocore/lemp:7.4
      - name: "[8.0] Build and push"
        id: docker_build_80
        uses: docker/build-push-action@v2
        with:
          push: true
          file: 8.0.Dockerfile
          tags: adhocore/lemp:8.0-alp3.13,adhocore/lemp:8.0
      # - name: "[8.1] Build and push"
      #   id: docker_build_81
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     file: 8.1.Dockerfile
      #     tags: adhocore/lemp:8.1-rc
